
[[developer-evaluation-and-constraint-solving]]
= Evaluation and Constraint Solving

This chapter will demonstrate how we evaluate formulas in the context of a formal model. It also demonstrates how we can use ProB's constraint solver.

== Evaluation
Several classes offer an `eval` method, the result depends on the specific class. We have already seen how we can evaluate an expression or prediacte in a state to retrieve state values. But we are not limited to variables, we can actually ask for any expression. Say in a state x the value of a is 7 and the value of b is 5. We can then ask ProB for the value of the expression a + b.

[source, groovy]
----
x.eval("a + b") // returns 12 if a=7 and b=5 in state x
x.eval("a < b") // returns FALSE
x.eval("#z.z<a & z<b") // returns TRUE (z=6)
----

The input of eval is either an instance of IEvalElement or a String. If the input is a String, it will be parsed with the same formalism as the model. This means, if we are in the context of  a classical B model, strings are treated as classical B formulas, if we are in the context of an EventB model a string is parsed as Event-B, etc.

If we plan to submit the same formula more than once, we should consider turning it into an instance of `IEvalElement` because this saves parsing the string multiple times. Each formalism has its own implementation of the IEvalElement interface. Once a string has been turned into an `IEvalElement`, it can be evaluated in any formalism.

[source, groovy]
----
\\ classicalb_x is a classical B state
\\ eventb_x is an Event B state
classical_b.eval("2**4") // 16
eventb_x.eval("2**4") // Type Error
cb_eval_element = new ClassicalB("2**4")
classical_b.eval(cb_eval_element) // 16
eventb_x.eval(cb_eval_element) // 16
eventb_x.eval("2**4" as ClassicalB)  // 16
eventb_x.eval(new ClassicalB("2**4"))  // 16
----

Trace also implements `eval`, but instead of evaluating the expression or predicate in a single state, it will evaluate it for the whole trace, i.e., it will return a list of results. The results are tuples containing the state ID and the result.  In addition to the `eval` method a trace also has a method `evalCurrent()`, which evaluates a formula in the current state of the trace.

The `StateSpace` class is responsible for actual evaluation, it provides an eval method that takes two arguments, a state Id and a list of `IEvalElements`. It returns a corresponding list of `EvalResult` objects.

This means, that we can evaluate multiple expressions and predicates in one go. This is important to avoid communication overhead with Prolog.

Note that there is no eval method that takes a single formula and evaluates the formula for every known state. We decided that using the same name for a method with that semantics would be too dangerous if we call it accidentally on a big state space. However, there is a method `evaluateForEveryState`, which actually evaluates a formula in every known state. There is also a method `evaluateForGivenStates` that takes a list of state IDs and a list of `IEvalElements` and evaluates each formula for each state.

As mentioned, the result of evaluation is an instance of the `EvalResult` class.

[source, groovy]
----
r = x.eval("base**4") // x is some state id, base is a B variable
r.getClass()          // class de.prob.animator.domainobjects.EvalResult
r.getValue()          // if in state x the value of base is 2
              // then we get "16" (as a String)
----

Note that we could also evaluate predicates, e.g., `base < 3`.

== Constraint Solving

Constraint solving is very similar to evaluation, the difference is that constraint solving only uses types from a model, but not an actual state. For example, we could ask which value b should have to satisfy the equation `b * 4 = 16` or we could ask for the set of all possible values of b `{b | b * 4 = 16}`, which will return `{-4,4}`.
The constraint based solver can be controlled through the `CbcSolveCommand`. It is very similar to evaluation. In fact, `eval` will also try to find a solution for free variables.

[source, groovy]
----
r = x.eval("b**4 = 16")    // x is some state id, b is a fresh variable
r.getValue()               // "TRUE"
r.getSolutions()           // A hashmap containing variable-value bindings
r.getSolutions().get("b")  // "-2"
----


We can also solve formulas with multiple variables and we can translate results to a unicode representation.
[source, groovy]
----
r = x.eval("{a,b|a < 100 & b:NAT & a>b & b ** 4 = a}")
r.getValue()                                              // {(16|->2),(81|->3)}
de.prob.unicode.UnicodeTranslator.toUnicode(r.getValue()) // {(16↦2),(81↦3)}
----

However evaluation is only applicable in the context of a state. If we want to solve constraints outside of a state, we have to use `CbcSolveCommand`.

[source, groovy]
----
f = "{a,b|a < 100 & b:NAT & a>b & b ** 4 = a}" as EventB
c = new CbcSolveCommand(f)
sspace.execute(c)
c.getResult()
----

Of course we can introduce some syntactic sugar

[source, groovy]
----
def solve(model, fstring) {
 f = model.parseFormula(fstring) // use correct formalism
 c = new CbcSolveCommand(f)
 model.getStateSpace().execute(c)
 c.getResult()
}
----

Note that Groovy can be very helpful to create small domain specific languages. For example we can create a small DSL to manipulate predicates.

[source, groovy]
----
String.metaClass.and = {b -> "("+delegate+") & ("+b + ")" }
not = { "not("+it+")" }
String.metaClass.implies = {b -> "("+delegate +") => (" + b + ") "}
ArrayList.metaClass.conj = { delegate.collect{it.toString()}.inject {a,b -> a & b} }
----

The first line changes the behavior of the `&` operator for strings.  The second line introduces a negation. The third line introduces an `implies` method to the String class.  Finally we add a `join` method to the ArrayList class allowing us to turn a list of predicates into a conjunction.

[source, groovy]
----
a = "x < 9"
b = "2 = y"
a & b // result is "(x < 9) & (2 = y)"
not(a & b) // result is "not((x < 9) & (2 = y))"
a.implies b // result is "(x < 9) => (2 = y)"
["x = 1","y = 2","x < y"].join() // result is "((x = 1) & (y = 2)) & (x < y)"
----

The constraint solver is a versatile tool that can be used in many situations, for instance, we could use it to identify events that are dead. A dead event find out if the guard G of an event contradicts the invariant `J`, i.e., there is a solution for `J ➝ ¬G`.

[source, groovy]
----
def dead_event(model, component, name) {
 def invariant = model.getComponent(component).getInvariant().conj()
 def guard = model.getComponent(component).getEvent("name").guards.conj()
 def predicate = invariant.implies(not(guard));
 solve(model,predicate)
}
----
