asciidoctor:
  stage: build
  image: asciidoctor/docker-asciidoctor:1.34
  before_script:
    - apk update
    - apk add graphviz
  script:
    - make -j2
  artifacts:
    paths:
      - build

upload:
  stage: deploy
  only: 
    - master@general/stups/prob2_doc
  image: alpine:3
  before_script:
    - apk update
    - apk add lftp openssh-client
  script: LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set sftp:auto-confirm yes; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/handbook/prob2/; mput -e build/*.html build/*.pdf; mput -e -O images/ build/images/*; exit"
