[[prob-for-rodin]]
=== ProB for Rodin

Currently there are two versions of ProB available for Rodin.

[[prob-1-for-rodin]]
==== ProB (1) for Rodin

The first one is based on the old Java API and supports
http://wiki.event-b.org/index.php/Rodin_Platform_2.8_Release_Notes[Rodin
2.8] and
http://wiki.event-b.org/index.php/Rodin_Platform_3.3_Release_Notes[Rodin
3.3]. The update site comes built in into Rodin, see
<<tutorial-rodin-first-step,the tutorial on installing ProB for
Rodin>>. Nightly releases of this versions are also available on the
<<download,Download>> page.

[[prob-2.0-for-rodin]]
==== ProB 2.0 for Rodin

The second, still experimental, one is based on the new
<<prob-java-api,ProB Java API>> (aka ProB 2.0). Because the UI
components provided by the <<prob-java-api,ProB Java API>> are based
on web technologies, we were able create a simple plugin for the Rodin 3
tool that provides the user with all of the functionality of ProB within
Rodin. The plugin uses views with embedded Eclipse SWT browsers to
access the user interface components that are shipped with the
<<prob-java-api,ProB Java API>> library. Details about nightly
releases of this versions is also available on the
<<download,Download>> page.

[[multi-simulation-for-rodin-based-on-prob]]
==== Multi-Simulation for Rodin based on ProB

There is now also a
http://users.ecs.soton.ac.uk/vs2/ac.soton.multisim.updatesite/[Multi-Simulation
Plug-in] available for Rodin. It enables discrete/continuous
co-simulation.

[[other-plug-ins-for-rodin]]
==== Other Plug-Ins for Rodin

[[prover-evaluation]]
===== Prover Evaluation

This Plug-in is available at the update site
http://nightly.cobra.cs.uni-duesseldorf.de/rodin_provereval/[http://nightly.cobra.cs.uni-duesseldorf.de/rodin_provereval/]
and is capable to evaluate a variety of provers or tactics on a
selection of proof obligations.

[[camille]]
===== Camille

We also develop the Camille text-editor for Rodin. A preliminary version
of Camille for Rodin 3.3 is available at the nightly update site:
http://nightly.cobra.cs.uni-duesseldorf.de/camille/[http://nightly.cobra.cs.uni-duesseldorf.de/camille/].
The regular update site
(http://www.stups.uni-duesseldorf.de/camille_updates[http://www.stups.uni-duesseldorf.de/camille_updates])
is preconfigured within Rodin. More information can be found on the
http://wiki.event-b.org/index.php/Camille_Editor[Camille site at
event-b.org].
