:wikifix: 2
ifndef::imagesdir[:imagesdir: ../../asciidoc/images/]
[[prob-for-event-b]]
= ProB for Event-B

In addition to classical B (aka B for software development), ProB also
supports Event-B and the Rodin platform. ProB can be installed as a
plugin for Rodin. Once installed, one can
<<tutorial-rodin-exporting,export contexts and models>> as *.eventb
files and use them within ProB Tcl/Tk and the command-line version
<<using-the-command-line-version-of-prob,probcli>>.

See the tutorial pages for more information about using ProB for
Event-B:

* link:/Tutorial_Rodin_First_Step[Starting ProB for Rodin and first
animation steps]
* link:/Tutorial_Rodin_Parameters[Important Parameters of ProB for
Rodin]
* link:/Tutorial_Rodin_Exporting[Exporting Rodin Models for ProB
Classic]
* <<tutorial-symbolic-constants,Using the Symbolic Contants Plugin>>
* <<tutorial-disprover,Using the ProB (Dis-)Prover>>
* link:/Tutorial_LTL_Counter-example_View[Visualization of LTL
Counter-examples in Rodin]

The http://handbook.event-b.org[Rodin handbook] also contains material
about ProB:

* http://handbook.event-b.org/current/html/tut_building_the_model.html#tut:prob[Finding
Invariant Violations with ProB]
* http://handbook.event-b.org/current/html/tut_populate_context.html#a0000000094[Finding
Solutions to Axioms]