[[dependency_injection]]
== Dependency Injection

We have decided to use the Guice framework for dependency injection. Although this is just an implementation detail  it is important to get a basic understanding of how it works and why we use it in order to build tools on top of ProB 2.0. A more complete introduction to dependency injection and the Guice framework can be found in https://dl.acm.org/citation.cfm?id=1795686[Dependency Injection by Prasanna] and https://github.com/google/guice[the Guice website].

Dependency injection is used when we create an instance of a class. As an example, we will use the `Api` class. The class depends on a class that constructs factories which construct model objects from files. It also depends on a provider that can create instances of `IAnimator`, which coordinates the execution of commands.

There are several possible ways to setup the dependencies. We could just create the dependency inside the constructor

[source, java]
----
public Api() {
   this.modelFactoryProvider = new FactoryProvider();
   this.animatorProvider = new AnimatorProvider();
}
----

But unfortunately the `FactoryProvider` requires four concrete Factory classes, `ClassicalBFactory`, `CSPFactory`, `EventBFactory` and `TLAFactory`. This would lead to a very intertwined code. Also it would become very hard to test the code in isolation.

A better way would be to pass in the dependencies of a class as parameters of the constructor

[source, java]
----
public Api(FactoryProvider modelFactoryProvider, Provider<IAnimator> animatorProvider) {
   this.animatorProvider = animatorProvider;
   this.modelFactoryProvider = modelFactoryProvider;
}
----

Now we moved the burden of creating the dependencies to the code that calls the constructor. This is very useful in a test, where we can now pass whatever we want when we setup the object. For instance, if we want to test the interaction of the `Api` with the animator provider, we could just use null as the `modelFactoryProvider` and a mock object as the `animatorProvider`. This mock object could simulate the real provider without actually starting up probcli.

But we only moved the problem one level up. However, the class that requires `Api` simply does the same thing. Its constructor takes an Api instance as a parameter.

If done by hand this approach would lead to a very complicated top level object, where we construct all the objects and then create a potentially complex object graph.

This is where dependency injection frameworks like Guice or Spring come into play. We annotate the constructor with @Inject and leave object instantiation to Guice.


[source, java]
----
@Inject
public Api(final FactoryProvider modelFactoryProvider, final Provider<IAnimator> animatorProvider) {
  this.animatorProvider = animatorProvider;
  this.modelFactoryProvider = modelFactoryProvider;
}
----

We can still manually construct the object for testing purposes, but in the actual application, instead of calling new, we use a so called Injector. If we ask the Injector to construct an Object, it will automatically setup all dependencies.  The injector is configured using so called modules.

If you build tools on top of ProB 2.0 you will likely require some of ProB's objects, so you have to interact with Guice to get proper objects.

CAUTION: Never create ProB objects whose constructor is annotated with @Inject by calling new unless you are writing a test.

The correct way is to get the injector and ask it for an instance. The `de.prob.Main` class contains the application injector. So if you want to get an instance of the Api class you would do it like this:

[source, java]
----
Api api = Main.getInjector().getInstance(Api.class);
----

If you want to use Guice in your own tool, you can create an Injector and tell ProB to use it.

[source, java]
----
Module myModule = new MyModule();
Injector myInjector = Guice.createInjector(Stage.PRODUCTION,
                                               mymodule,
			                                         new MainModule());
Main.setInjector(myInjector);
----

`MainModule` is ProB's default module. It is a composition of other modules. If you want to use ProB as it is, you typically use `MainModule`. But you can change parts of ProB by exchanging ProB's modules with your own configuration. For instance, you could configure the injector to use your own implementation of the `Api` class instead of ProB's version.
