[[links]]
= Links

[[books]]
== Books

* http://www.jpbowen.com/publications/thes-b.html[The B-Book: Assigning
programs to meanings, by Jean-Raymond Abrial] (link is to a review by
Jonathan Bowen)
* http://www.palgrave.com/science/computing/schneider/[The B-Method: An
Introduction, by Steve Schneider]
* http://www.event-b.org/abook.html[Modeling in Event-B: System and
Software Engineering, by Jean-Raymond Abrial] (the Bee book)

[[papers]]
== Papers

* https://www3.hhu.de/stups/downloads/pdf/[ProB Publications]
* http://en.wikipedia.org/wiki/B-Method[B-Method in Wikipedia]
* http://www.bmethod.com/[B-Method Site] from ClearSy
* http://www.fm4industry.org/index.php/Can_FM_tools_manage_large_industrial_problems%3F[Can
FM tools manage large scale industrial problems ?]
* http://www.data-validation.fr[Data Validation]

[[prob]]
== ProB

* <<modelling-examples,Examples for ProB>> (along with screenshots and
explanations)
* http://www.ecs.soton.ac.uk/~mal/systems/prob.html[Old web page of
ProB] (in Southampton; use for releases prior to 1.2)
* http://www.fm4industry.org/index.php/Productivity_Improvement_of_Data_Consistency_in_Transportation_Models[Link
to Success Story (written by Cetic)]
* https://groups.google.com/d/forum/prob-users[prob-users group]

[[tools-using-prob]]
== Tools using ProB

* https://www.clearsy.com/en/our-tools/clearsy-data-solver/[ClearSy Data Solver]
* http://www.data-validation.fr/data-validation-in-the-railways/[DTVT -
Data Table Validation Tool] for Alstom by ClearSy
* OLAF data validation tool by ClearSy for Alstom and SNCF
* Dave data validation tool by ClearSy for General Electric Transportation
* https://github.com/plues/plues[PLUES] tool for university course
validation
* http://safecap.cs.ncl.ac.uk/index.php/Safecap_Project_Wiki[SafeCap]
* http://wiki.event-b.org/index.php/IUML-B[iUML Statemachines]
* http://users.ecs.soton.ac.uk/vs2/ac.soton.multisim.updatesite/[MultiSimulation
Plug-In for Rodin]
* http://www.beta-tool.info/user_guide.html[Beta]
* http://www.macs.hw.ac.uk/~mtl4/Publications.html[HRemo (see PhD
thesis)]
* http://dx.doi.org/10.14279/depositonce-2502[Message Choreography Model
Animation and Test Case Generation (see PhD thesis; Chapters 5 and 6)]
http://link.springer.com/article/10.1007%2Fs10270-012-0272-x[SSM article
(2014)]
* http://b4msecure.forge.imag.fr[B4MSecure]
* http://genisis.forge.imag.fr[GenISIS]
* http://blog.aymericksavary.fr/?page_id=209[VTG] (Vulnerability Test
Generator, see
http://blog.aymericksavary.fr/wp-content/uploads/2011/10/presentation.pdf[Rodin
Workshop 2012 presentation] and
http://blog.aymericksavary.fr/wp-content/uploads/2014/06/Présentation.pdf[2014
presentation])
* CODA https://arxiv.org/abs/1305.6112v1[arXiv article]
* There is also some intitial effort to
http://pure.au.dk/portal/en/publications/interpreting-implicit-vdm-specifications-using-prob(19de7f9f-1d9a-483c-b2e7-285c0d0edc63).html[use
ProB for implicit VDM specifications] presented at
http://wiki.overturetool.org/index.php/12th_Overture_Workshop[the 12th
Ouverture Workshop].
* https://github.com/ValerioMedeiros/BEval[BEval]
* https://github.com/ValerioMedeiros/BTestBox[BTestBox]
* http://wiki.event-b.org/index.php/MBT_plugin[MBT plugin] for
model-based testing within Rodin
* https://rajivmurali.github.io/UsecasePro/[UseCasePro], see article in
the
http://eprints.ncl.ac.uk/file_store/production/229541/A4269E59-6B4A-485E-8E63-E164802DFADD.pdf[proceedings
of the 2016 Workshop on Formal and Model-Driven Techniques for
Developing Trustworthy Systems]
* http://bibbase.org/network/publication/lausdahl-ishikawa-larsen-interpretingimplicitvdmspecificationsusingprob-2015[Animating
implicit VDM specifications inside Ouverture]
* http://www.ovado.net[Ovado] (as second tool chain)
* https://github.com/tofische/cucumber-event-b/[Cucumber-Event-B] tool to run high-level tests

[[related-tools]]
== Related Tools

* http://www.atelierb.eu/[Atelier B]
* http://www.event-b.org/[Event-B and Rodin Wiki]
(http://wiki.event-b.org/index.php/Rodin_Platform_Releases[Platform
Releases], http://wiki.event-b.org/index.php/Main_Page[Documentation]),
http://sourceforge.net/projects/rodin-b-sharp/[Rodin Sourceforge Site]
* https://github.com/utwente-fmt/ltsmin/releases[LTSmin releases
(including versions for prob)]
* http://lifc.univ-fcomte.fr/~btatibouet/PERSO/JBTOOLS/InstallPlugIn/InstallPlugIn.html[jbtools]
* http://www.b4free.com/[B4Free] tools for the development of B models
* http://www.loria.fr/~cansell/cnp.html[Click n Prove]
* https://github.com/edwardcrichton/BToolkit[B Toolkit]
* http://www.ecs.soton.ac.uk/~cfs/umlb.html[U2B] UML to B translation
tool
* http://research.microsoft.com/en-us/um/people/lamport/tla/tla.html[TLA+]
(http://research.microsoft.com/en-us/um/people/lamport/tla/tools.html[tools
for TLA+])
* https://spivey.oriel.ox.ac.uk/mike/fuzz/[The fuzz type-checker for Z]
* https://www.cs.ox.ac.uk/projects/fdr/[The FDR3 CSP refinement checker]
* https://github.com/leuschel/bbedit-prob[BBedit Language modules for B,
TLA+, CSP and Prolog]
* https://en.wikipedia.org/wiki/List_of_model_checking_tools[Model
checking tools]

[[testimonials]]
== Testimonials

* http://www.deploy-project.eu/pdf/D41-Siemens-final-full.pdf[Data
validation at Siemens, Jérôme Falampin]: "The work done with ProB is a
great success. Thanks to the automatization and ProB, the wayside data
validation is quicker, easier and complete." More details and academic
papers can be found on our page
<siemens-data-validation-with-prob,Siemens Data Validation with
ProB>>.
* http://dl.acm.org/citation.cfm?doid=2406336.2406351[Pacemaker model by
Mery and Singh]: "ProB was very useful in the development of the
pacemaker specification, and was able to animate all of our models and
able to prove the absence of error (no counterexample exist). The ProB
model checker also discovered several invariant violations, e.g.,
related to incorrect responses or unordered pacing and sensing
activities. It was also able to discover a deadlock in two of the
models, which was due to the fact that “clock counter” were not properly
recycled, meaning that after a while no pacing or sensing activities
occur into the system. Such kind of errors would have been more
difficult to uncover with the prover of RODIN tool.""
* http://www.data-validation.fr/data-validation-reverse-engineering/[Reverse
engineering using ProB at ClearSy]: "Data validation principles have
been applied recently to a railways reverse-engineering project with
great success. B and ProB have demonstrated again how efficient they are
when used in combination."..."This problem was solved elegantly by
using data validation principles: a B model representing the two graphs
and their properties were elaborated, and ProB used for finding a
solution."
* http://www.ncl.ac.uk/computing/research/publication/197269[Safecap
tool paper by Iliasov, Lopatkin and Romanovsky]: "One of the larger
examples we have tackled is the Carlisle Citadel station with the North,
South, and Caldew junctions. The modelled fragment is 2.6km long and
comprises 70 train detection circuits, 63 points, 79 routes and 161
valid paths. The translation from a scanned PDF drawing and printed
control tables took 45 man-hours. The verification of the topology
theory constraints using ProB took just over 6 minutes on a PC with i7
3730 CPU and utilized just under 2GB of RAM. The Why3 verification of
the same theory takes approximately 70 minutes. The control table theory
is verified under 20 seconds by ProB and not verified completely, with
the current translation of conditions, using Why3."
* http://www.erts2014.org/Site/0R4UXE94/Fichier/erts2014_1B2.pdf[Innovative
Approach for Requirements Verification of Closed Systems by Reis,
Bicknell, Butler, Colley]: "The Event-B model can be animated within
Rodin using the BMotion Studio tool, which is part of ProB. Using the
tool, it is possible to generate an animated front-end to the simulation
of the model in the form of a user-friendly graphical interface, which
corresponds to the system’s GUI (see Figure 4). The user can interact
directly with this animated front-end, while the tool continues to run
the formal analysis in the background, reacting to user choices and
checking the model and invariants at each step. This was utilised during
the case study, to produce a representation of the GIU provided as part
of the end-user system. As this graphical representation is tied to the
underlying Event-B model, it can not only be used to run through the
model and confirm that the model is the correct representation of the
system, but can also be used to explore further scenarios. This
graphical representation of the system can be used without necessarily
requiring any experience with the Event-B language or the toolset."
* http://dl.acm.org/citation.cfm?id=2480314[ProZ for Modelling Safety
Properties of Interactive Medical Systems by Bowen and Reeves]: "In
this paper we have shown how temporal logic and invariants describing
safety properties of interactive medical devices can be investigated
within the ProZ tool. We have given examples of checking for such
properties against a model of the T34 syringe pump and discussed some of
the results and challenges we have encountered using this approach. We
believe that using techniques such as these, and other model-checking
functionalities, contributes to supporting safer use of interactive
medical devices. That is we can use such techniques not just to help
develop better and safer systems (where such techniques are most
typically used) but also, as we have shown here, to investigate existing
devices to ensure they can be safely used within the clinical setting."
* ProB has been used “out-of-the-box” for Rodin theories by Thales for
railway interlocking models, building ProB BMotionStudio visualizations
on top. According to the
http://www.advance-ict.eu/sites/www.advance-ict.eu/files/Thales-Duesseldorf.pdf[Thales
slides of the Advance Industry Day 2014] ProB has a high technology
readiness level (TRL).
* ProB
http://smtcomp.sourceforge.net/2016/results-NIA.shtml?v=1467112059[wins
the NIA (non-linear integer arithmetic) division of the 2016 SMT
competition] (this is ProB out-of-the-box, without tuning and where SMT
formulas are translated to B)

[[other-links]]
== Other Links

* https://github.com/klar42/railground/[Railground Event-B Model]

[[translating-to-logic]]
== Translating to Logic

* http://legacy.earlham.edu/~peters/courses/log/transtip.htm[Translation
Tips]
* http://pages.cs.wisc.edu/~dyer/cs540/notes/fopc.html[Lecture Notes on
Translating to First-Order Logic]
* http://cs.nyu.edu/faculty/davise/guide.html[Guide to Axiomatizing in
First-Order Logic]
