ifndef::imagesdir[:imagesdir: ../../asciidoc/images/]
/Category:User_Manual[Category:User Manual]__NOTOC__

[[what-are-the-available-versions]]
== What are the available versions?

* The standalone Tcl/Tk Version of ProB (ProB Tcl/Tk)
* The standalone command-line version of ProB
(link:/Using_the_Command-Line_Version_of_ProB[probcli])
* The link:/Tutorial_Rodin_First_Step[ProB Plugin for Rodin/Eclipse]
* The online link:/ProB_Logic_Calculator[ProB Logic Calculator]

Both the standalone ProB Tcl/Tk and probcli can be downloaded together
(within a Zip archive or tarball together with examples) from our
link:/Download[Downloads page]. The online
link:/ProB_Logic_Calculator[ProB Logic Calculator] requires no
installation; just type in predicates and expressions into the web page.

There is also a
http://www.tools.clearsy.com/index.php5?title=ProB_etool_generation[plugin
for Atelier B], in order to use the standalone ProB Tcl/Tk Version on
http://www.atelierb.eu/[Atelier B] projects. It comes bundled with ProB
Tcl/Tk.

ProB is used within a few other tools, such as
http://wiki.event-b.org/index.php/IUML-B[iUML-B] or
http://safecap.sourceforge.net/index.shtml[SafeCap].

We are also developing a new Java-based API called
link:/ProB_2.0_Tutorial[ProB 2.0], which is a high-level wrapper for the
command-line version
link:/Using_the_Command-Line_Version_of_ProB[probcli].

[[which-version-should-i-use]]
== Which version should I use?

The standalone version Tcl/Tk of ProB contains a richer set of features
than the Rodin version and also works on other formalisms than Event-B
(e.g., classical B, Z, CSP, B||CSP, Promela, ...). If you want to do
animation and model checking of Event-B models, the Rodin version might
be enough. The Rodin version contains a translation tool from Rodin into
Event-B package files that can be used within the standalone version of
ProB. Use the probcli version if you want to write batch scripts or
prefer working from the command-line.

[[installation-instruction-for-prob-standalone]]
== Installation Instruction for ProB (Standalone)

Note: we have specific
link:/Windows_Installation_Instructions[Windows_Installation_Instructions].
These here are the generic instructions.

* Obtain your platform specific ProB distribution from
link:/Download[Downloads]. Decompress and expand the ProB directory if
necessary. Do not change the location and structure of the files and
directories within ProB (apart from the Machines directory)! On Windows
you just have to double-click the installer. The contents of the ProB
directory should look something like this:

`examples            lib     prob` +
`StartProB.sh        tcl`

On Windows, you will also have a subfolder called ``Microsoft.VC80.CRT''
containing the DLLs for the C runtime. Also, the binary is called
``ProBWin'' and not ``prob''.

* Be sure that you have Tcl/Tk installed (see, e.g.,
http://www.tcl.tk/software/tcltk/). With the latest version of ProB, you
have to install Tcl/Tk version 8.5.
For example, you can find a correct version of Tcl/Tk at
http://downloads.activestate.com/ActiveTcl/releases/8.5.18.0/.
* To load your own B machines you also need Java 7 or newer runtime or better JDK.
* Note: you can skip this step if you do not wish to use the
visualization commands. Install the ``dot'' program and ``dotty'' viewer
from AT&T's Graphviz package (http://www.graphviz.org/ or
http://www.research.att.com/sw/tools/graphviz/).
By default, ProB will
open the ``dotty'' program to visualize the graphs, but postscript
viewers (such as gv) are also supported. So, you do not need to install
dotty if you don't want to; but it is probably easiest to install the
entire Graphviz package.
* Change to the ProB directory and then start up prob. In Windows you
can simply double-click on the ProBWin Application. On Mac OS X you may
have to type 'limit data unlimited' (in tcsh) or 'ulimit -d unlimited'
(in bash) before launching ProB using the Terminal Application. The
distribution contains a script StartProB.sh which does this for you
(note you may have to do chmod u+x StartProB.sh before launching it from
the command-line).
* Now you should be able to open some of the B Machines in the Machines
directory. You should then be able to initialize the machines and
animate them. Have a look at the supplied Machines in the examples
directory. Have fun ! Please report bugs!

[[checklisttroubleshooting]]
=== Checklist/Troubleshooting

* Java: be sure to have Java 7 or newer installed. Otherwise you will
not be able to parse your own classical B machines as our parser is
written in Java.

* Tcl/Tk: be sure to have a suitable version of TclTk installed. In
general you should install at least 8.5.
You also need the 64 bit version of Tcl/Tk for 64 bit
versions of ProB.

* GraphViz: in order to make use of the graphical visualization
features, you need to install a version of GraphViz suitable for your
architecture. Then use the command ``Graphical Viewer Preferences...''
in the Preferences Menu to set or check the following preferences:
** Path/Command for dot program
** Path/Command for dot viewer (e.g., dotty)

Note: you can use the ``Pick'' button to locate the dot program and the
dot viewer. See more information about the
link:/Graphical_Viewer[Graphical Viewer here].

[[installation-instruction-for-prob-rodin-plugin]]
== Installation Instruction for ProB (Rodin Plugin)

The following movie shows how to install the ProB Rodin Plugin.

http://www.stups.uni-duesseldorf.de/ProB/Install.swf[`http://www.stups.uni-duesseldorf.de/ProB/Install.swf`]
