

[[using-prob-with-z3]]
== Using ProB with Z3

The current nightly versions of ProB can make use of
https://github.com/Z3Prover/z3[Z3] as an alternate way of solving
constraints.

[[how-to-use-z3-within-prob]]
=== How to use Z3 within ProB

One can start a REPL (Read-Eval-Print-Loop) by starting probcli with the
`-repl` command line option. Any predicate preceded with `:z3` will be
solved by Z3. The full integration of Z3 and ProB’s kernel can be
enabled by setting the corresponding preference by passing

`-p SMT SUPPORTED INTERPRETER TRUE`

on the command line.

[[how-to-install-z3-for-prob]]
=== How to install Z3 for ProB

First of all, download a nightly build of ProB from the
<<download,Downloads>> page. To connect Z3 to ProB you also need the
proper extension. For Linux and Mac OS, the extension is build by on our
infrastructure and ships with the regular ProB download. For Windows,
you can download it from the following URLs:

* https://www3.hhu.de/stups/downloads/z3interface/windows32/z3interface.dll[32bit]
* https://www3.hhu.de/stups/downloads/z3interface/windows64/z3interface.dll[64bit]

and place it in the "lib" folder of the ProB nightly build.

In addition to ProB, you need to install Z3 by downloading it from
https://github.com/Z3Prover[Z3's GitHub page]. Currently, ProB is linked
against the stable release 4.4.1 of Z3. Inside the zip file you will
find a folder called "bin" with the z3 binary and the belonging
libraries inside.

These libraries have to be made available to ProB. On Linux or Mac, this
can either be done by placing them in an appropriate folder (like
/usr/lib or /usr/local/lib) or by setting an environmental variable
(like LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac). On Windows,
you can place z3.dll in the main folder of the ProB distribution, i. e.,
on the same level as the lib directory, not inside it. If the libraries
can not be loaded, ProB will answer with "solver_not_available" when
Z3 is queried.

[[what-can-be-translated-z3]]
=== What can be translated

Currently, the Z3 translation is unable to cope with the following
constructs:

* Strings
* Generalised union, generalised intersection
* Generalised concatenation
* Permutation
* Iteration and Closure
* Projection

When using Z3 alone, the solver will report
"unsupported_type_or_expression" if it can not handle parts of a
constraint.

When used together with ProB, everything Z3 can not be coped with will
be handled by ProB alone automatically.

[[examples-z3]]
=== Examples

Using the repl, one can try out different examples.

First an example which can be solved by Z3 and not by ProB:

....
>>> X0)
### Warning: enumerating X : INTEGER : inf:sup ---> -1:3
Existentially Quantified Predicate over X,Y is UNKNOWN
[FALSE with ** ENUMERATION WARNING **]
....

Using the Z3 translation it can be solved:

....
>>> :z3 X>> (2|->4):{y|#x.(y=(x|->x+2))}
PREDICATE is TRUE
....

This one cannot be solved by Z3:

....
>>> :z3 (2|->4):{y|#x.(y=(x|->x+2))}
PREDICATE is UNKNOWN: solver_answered_unknown
....

Here an example that shows that Z3 can be used to solve constraints and
obtain solutions for the open variables:

....
>>> :z3 {x} /\ {y} /= {} & x:1000000..20000000 & y>=0 & y<2000000
PREDICATE is TRUE
Solution:
x = 1000000
y = 1000000
....

[[more-details-z3]]
=== More details

A paper describing the integration of ProB and Z3 has been submitted to
iFM 2016. You can download the

* https://www3.hhu.de/stups/downloads/z3interface/rawdata[raw data] from
our benchmarks including the R scripts to generate the
* https://www3.hhu.de/stups/downloads/z3interface/output[resulting
graphs].
