[[prolog-coding-guidelines]]
= Prolog Coding Guidelines

[[general-guidelines]]
General Guidelines
------------------

Please ensure that there are no compilation errors or warnings when
checking in. Also, try to ensure that there are no errors when loading
the files in Spider (Eclipse). Ideally, try to get rid of warnings as
well.

Have a look at the paper by
/http://www.ai.uga.edu/mc/plcoding.pdf_Covington_et_al.[http://www.ai.uga.edu/mc/plcoding.pdf
Covington et al.] on Prolog coding guidelines.

Concerning naming of identifiers: try to use names for constants,
functors and predicates that are unique and not a prefix of other names.
This ensures that one can quickly find all uses/definitions with grep or
BBEdit.

[[module-information]]
Module Information
------------------

Every module should be annotated with module information. This is used
by our coverage analysis tool.

....
:- module(MYMODULE, [  exported_predicate/arity, ... ]).

:- use_module(tools).

:- module_info(group,kernel).
:- module_info(description,'This module does wonderful things').
....

[[unit-tests]]
Unit Tests
----------

Unit tests should be setup using the self_check module.

....
:- use_module(self_check).
....

Afterwards you can use the following to add new unit tests:

....
:- assert_must_succeed((bsets_clp:empty_sequence([]))).
:- assert_must_fail((bsets_clp:empty_sequence([int(1)]))).
....

These tests can be run manually from the ProB Tcl/Tk version, from the
command-line using the -self_check command. They will also be
automatically run on our jenkins server after committing.

[[errors]]
Errors
------

Errors should be raised using one of the `add_error` predicates in the
`error_manager` module. This will ensure that the errors are brought to
the attention of the user in an appropriate way, depending on whether
the Rodin, the Tcl/Tk, the command-line version is run and also
depending on whether the tool is in testing and/or batch mode.

Note: for internal errors that should never occur use the
`add_internal_error` predicate. This ensures that the
https://www3.hhu.de/stups/internal/coverage/html/[coverage information]
is shown accordingly (in blue rather than red in the highlighting and
this also affects coverage statistics).

[[preferences]]
Preferences
-----------

Preferences should be declared in the `preferences` module. Each
preference must have a default value, a textual description, a type and
category. Optionally, a short string for setting the preference from the
command-line can be given (using the `-p PREF VALUE` switch).

[[git]]
Git
---

* before committing ensure that probcli can be built (make prob);
otherwise git bisect gets annoying to use (one can use git bisect skip
to some extent, but it is annoying)
* run integration tests before pushing your changes (ideally also before
committing to avoid later issues with git bisect); ideally you should
run as many tests as possible, but at least those affecting the parts
you have changed. See alias below to start the test REPL. The command
"test" then starts the ProB Test REPL. Type something like "tickets"
to run all non-regression tests related to tickets.
* as a rule of thumb: use rebase before pushing your changes to gitlab,
especially when you only have one real commit.

[[useful-bash-aliases]]
Useful Bash Aliases
-------------------

To run probcli from sources:

`alias probsli='rlwrap sicstus -l $PROB_SOURCE_DIR/prob_cli.pl --goal "``go_cli.`"`-a'`

To run probcli with the REPL from sources:

`alias seval='cd $NEWPROBDIR; rlwrap sicstus -l $PROB_SOURCE_DIR/prob_cli.pl --goal "``go_cli.`"`-a -repl -init -p WARN_WHEN_EXPANDING_INFINITE_CLOSURES 0 -p CLPFD TRUE'`

To run ProB Tcl/Tk from sources:

`alias prob='cd $PROB_SOURCE_DIR; unlimit; sics -Dprob_profile=true -l $PROB_SOURCE_DIR/prob_tcltk.pl --goal "``go.`"`'`

To run the ProB Test REPL from sources:

`alias test='cd $PROB_SOURCE_DIR/..; rlwrap sicstus -Dprob_safe_mode=true -l $PROB_SOURCE_DIR/test_runner.pl --goal "``test_repl.`"`'`
