:wikifix: 2
ifndef::imagesdir[:imagesdir: ../../asciidoc/images/]
[[getting-involved]]
= Getting Involved

:category: Developer_Manual


[[the-prob-java-core-and-ui]]
The ProB Java Core and UI
^^^^^^^^^^^^^^^^^^^^^^^^^

see the README in our https://github.com/bendisposto/prob[Github
Repository]

[[the-prolog-sources]]
The Prolog Sources
^^^^^^^^^^^^^^^^^^

If you want to contribute to the Prolog part of ProB, if you want to
extend the ProB API, or need them as reference, you need the Prolog
sources which can be downloaded from
https://www3.hhu.de/stups/downloads/prob/source/[https://www3.hhu.de/stups/downloads/prob/source/].
To compile the sources you need a
http://www.sics.se/isl/sicstuswww/site/index.html[SICStus Prolog]
licence.

[[running-prob-from-prolog]]
Running ProB from Prolog
^^^^^^^^^^^^^^^^^^^^^^^^

You first need to download and install
http://www.sics.se/isl/sicstuswww/site/index.html[SICStus Prolog].
Evaluation licenses (30-days) are available. You need SICStus 4.2 or
newer (we will switch to SICStus 4.3 in summer or autumn of 2014).

You need the password to download SICStus then run
`sudo ./InstallSICStus` and provide the site name, license code and
expiration date. Be sure to add the SICStus binaries to your PATH.

Probably you should also install a recent Active Tcl distribution.

Now, you need the ProB Prolog sources. If you have access to our Gitlab
server then the information is here:
http://tuatara.cs.uni-duesseldorf.de/prob/prob_prolog[http://tuatara.cs.uni-duesseldorf.de/prob/prob_prolog].

Now, add the following to your `.bash_login` file (at least on Mac OS;
supposing you cloned the Git repository into ~/git_root):

`export PROBDIR=~/git_root/prob_prolog` +
`export PROB_SOURCE_DIR=$PROBDIR/src` +
`alias prob='cd $PROB_SOURCE_DIR; sicstus -Dprob_profile=true -l $PROB_SOURCE_DIR/prob_tcltk.pl --goal "``go.`"`'`

Now, you can simply start ProB from the command-line and from source
with `prob`.

To start the Unit Test REPL, add the following to your `.bash_login`
file (at least on Mac OS):

`alias test='cd $PROBDIR; rlwrap sicstus -Dprob_safe_mode=true -l $PROB_SOURCE_DIR/test_runner.pl --goal "``test_repl.`"`'`

(It is recommended to install rlwrap so that you get a history of your
commands. If you don't want to install rlwrap just remove it from the
line above.)

Before using ProB for the first time from source you should build the
extensions. The minimal extensions are counter and user_signal. You can
build them using

`cd extensions/counter` +
`make` +
`cd ../user_signal` +
`make`

You could also build all extensions at once by going to the top of the
prob_prolog tree (i.e., the directory containing src and lib as
sub-directories) and then type

`make`

On Mac you may have to add a symbolic link to gawk in order to build the
ProZ fuzz extension:

`sudo ln -s /usr/bin/awk /usr/bin/gawk`

Now you can start the testing console using `test`. You can e.g. type
the number of a unit test to run it, or a test category such as
`tickets` to run all tests in that category.

[[running-the-prolog-tests]]
Running the Prolog Tests
^^^^^^^^^^^^^^^^^^^^^^^^

All Prolog tests are stored as facts in the file `test cases.pl`. Every
test has

* an identifier (a number); the last test added has the highest number
* a non-empty list of categories (such as unit, tickets,...)
* the test itself: the parameters to `probcli` needed to run the test
* a textual description of the test

There is a specific `test_runner.pl` file for running all Prolog unit
and integration tests. The test_runner also provides a REPL
(read-eval-print-loop) for running tests and collection of tests.

Supposing you have set the variable `PROBDIR` (see above) and have the
`rlwrap` tool, you can define the following alias (e.g., in your
`.bash_login` file on Mac OS X):

`alias test='cd $PROBDIR; rlwrap sicstus -Dprob_safe_mode=true -l $PROBDIR/src/test_runner.pl --goal "``test_repl.`"`'`

Now you can start the test runner:

....
$ test
...
SICStus 4.2.3 (x86_64-darwin-11.4.2): Fri Oct  5 15:58:35 CEST 2012
Licensed to SP4phil-fak.uni-duesseldorf.de
TEST ==> last.
...
All tests successful.
Walltime: 100 ms
....

Some useful commands are:

* last to run the last test added to `testcases.pl`
* all to run all tests
* cat to list all categories of tests (e.g., cbc, cbc_deadlock,...)
* cbc, cbc_deadlock, tickets, ... : to run all tests in that category
* type in a number to run the specific test with that number (see
`testcases.pl`)
* type in a range m-n to run all tests in that range
* v or vv to switch to verbose or very verbose mode
* q to quit the test runner (and stay in Prolog)
* x to quit the test runner and Prolog
* debug to switch on Prolog debug mode
* trace to force Prolog to start tracing as soon as an error occurs (if
you have switched to debug above then you will be able to inspect the
Prolog goal stack)