[[current-limitations]]
== Current Limitations

ProB in general requires all <<deferred-sets,deferred sets>> to be
given a finite cardinality. If no cardinality is specified, a default
size will be used. Also, unless finite bounds can be inferred by the
ProB constraint solver, mathematical integers will only be enumerated
within `MININT` to `MAXINT` (and ProB will generate enumeration
warnings in case no solution is found).

Other general limitations are:

* Trees and binary trees are specific to the AtelierB
tool and are only partially supported (the `STRING` type is now supported).

* Definitions (from the `DEFINITIONS` clause) with
arguments are supported, but in contrast to AtelierB they are parsed
independently and have to be either an expression, a predicate, or a
substitution; definitions which are predicates or substitutions must be
declared before first use.
Also: the arguments of `DEFINITIONS` have to
be expressions. Finally, when replacing DEFINITIONS the associativity is
not changed. E.g., with `PLUS(x,y) == x+y`, the expression
`PLUS(2,3)*10` will evaluate to 50 (and not to 32 as with Atelier-B).
Also, ProB will generate a warning when variable capture may occur.

* There are also limitations with refinements, as discussed below.

* The `VALUES` clause of `IMPLEMENTATION` machines is not yet
supported.

* Parsing: ProB will require parentheses around the comma, the
relational composition, and parallel product operators. For example, you
cannot write `r2=rel;rel`. You need to write `r2=(rel;rel)`. This allows
ProB to distinguish the relational composition from the sequential
composition (or other uses of the semicolon).

See the page <<using-prob-with-atelier-b,Using ProB with Atelier B>> for more details.

[[multiple-machines-and-refinements]]
=== Multiple Machines and Refinements

It is possible to use multiple B machines with ProB. However, ProB may
not enforce all of the classical B visibility rules (although we try
to). As far as the visibility rules are concerned, it is thus a good
idea to check the machines in another B tool, such as Atelier B or the
B-Toolkit.

While refinements are supported, the preconditions of operations are not
propagated down to refinement machines. This means that you should
rewrite the preconditions of operations (and, if necessary, reformulate
them in terms of the variables of the refinement machine). Also, the
refinement checker does yet check the gluing invariant.

Note however, that for Rodin Event-B models, ProB fully supports multi-level
animation and validation.
