:wikifix: 2
ifndef::imagesdir[:imagesdir: ../../asciidoc/images/]
[[editors-for-prob]]
= Editors for ProB

[[prob-tcltk-editor]]
ProB Tcl/Tk Editor
~~~~~~~~~~~~~~~~~~

ProB Tcl/Tk contains an editor in which syntax errors are displayed and
which can be used to edit B, CSP, Z and TLA+ models. The editor of
Tcl/Tk, however, has a few limitations:

* it can become very slow with long or very long lines
* the syntax highlighting can become slow with very large files. Hence,
syntax highlighting is automatically turned off in some circumstances
(when more than 50,000 characters are encountered or when a line is
longer than 500 characters).

It is possible to open the files in an external editor. You can setup
the editor to be used by modifying the preference ''Path to External
Text Editor'' in the Advanced Preferences list (available in the
_Preferences_ menu). You can then use the command ''Open FILE in
external editor'' in the _File_ menu to open your main specification
file with this editor. You can also use the command-key shortcut
"Cmd-E" for this.

[[launching-the-editor-in-probcli]]
Launching the editor in probcli
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The <<using-the-command-line-version-of-prob,probcli>> REPL
(read-eval-print-loop) supports the command `:e` to open the current
file in the external editor, as specified in the "EDITOR" preference.
You can set this preference using:

`probcli -repl -p EDITOR PATH`

In case errors occurred with the last command, this will also try and
move the cursor to the corresponding location in the file.

[[external-editors]]
External Editors
~~~~~~~~~~~~~~~~

[[vim]]
VIM
^^^

A https://github.com/bivab/prob.vim[VIM plugin for ProB is available].
It shows a quick fix list of parse and type errors for classical B
machines (.mch) using the
<<using-the-command-line-version-of-prob,command line tool probcli>>.
VIM has builtin syntax highlighting support for
https://github.com/vim/vim/blob/master/runtime/syntax/b.vim[B].

[[atom]]
Atom
^^^^

There is a package
https://atom.io/packages/language-b-eventb[language-b-eventb] available
for the Atom editor. It adds syntax highlighting and snippets for the
specification languages B and Event-B to Atom. It integrates with
probcli to obtain error markers for syntax and type errors.

[[bbedit]]
BBEdit
^^^^^^

Some https://github.com/leuschel/bbedit-prob[BBedit Language modules for
B, TLA+, CSP and Prolog] are available.

[[emacs]]
Emacs
^^^^^

A packageimage::b-mode.el.zip[] is available.
