

= ABZ 2016 Case Study

[[the-hemodialysis-machine-case-study]]
== The Hemodialysis Machine Case Study

This page provides additional information and resources for the paper we
have submitted for the http://www.cdcc.faw.jku.at/ABZ2016[ABZ 2016 case study track].

The full description of the case study can be found http://www.cdcc.faw.jku.at/ABZ2016/HD-CaseStudy.pdf[here].

[[resources]]
=== Resources

* http://www.cdcc.faw.jku.at/ABZ2016/HD-CaseStudy.pdf[ABZ 2016 Case Study Paper]

The original specification of the HD machine as PDF.

* https://www3.hhu.de/stups/prob/images/d/d3/HDMachine-160122.zip[HD Machine Event-B Model]

The zip file contains the HD machine Event-B model. You can import the
zip file directly into the Rodin platform as an Event-B project.

* https://www3.hhu.de/stups/prob/images/b/bf/Cosim-160122.zip[Co-Simulation Model of the Blood Flow Control]

The zip file of the co-simulation model contains a readme file that
explains what is included.

* https://www3.hhu.de/stups/prob/images/3/39/HDMachine-BMS-160122.zip[BMotion Studio Visualisation]

The zip file contains the domain specific visualisation of the HD
machine developed with BMotion Studio. You need to
http://www.stups.hhu.de/ProB/index.php5/BMotion_Studio_Download[download]
the latest version of BMotion Studio (v.0.2.7). Some instruction for
getting started with BMotion Studio can be find
http://www3.hhu.de/stups/handbook/bmotion/current/html/first_steps.html[here].

[[live-visualisation]]
=== Live Visualisation

* http://wyvern.cs.uni-duesseldorf.de/bms/hdmachine.html[BMotion Studio
Visualisation of the HD Machine]

If you have problems in running the visualisation, please contact Lukas
Ladenberger (ladenberger@cs.uni-duesseldorf.de)

[[links]]
=== Links

* http://www.stups.hhu.de/ProB/index.php5/BMotion_Studio[BMotion Studio for ProB Homepage]
* https://www3.hhu.de/stups/handbook/bmotion/current/html[BMotion Studio for ProB User Handbook]
* http://wiki.event-b.org/index.php/IUML-B[iUML-B Homepage]
* http://handbook.event-b.org/[Rodin Handbook]
